[tool.docgen]
style = "Google"        # Google | NumPy | reST
rewrite = false         # false = only missing
module_doc = true       # auto insert module docstring
coverage_min = 90

[tool.pydocstyle]
convention = "google"
add-ignore = ["D202"]
match = "(?!test_).*\\.py"

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203"]

